apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: appdeploy
  ports:
    - port: 8080
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: appdeploy
  template:
    metadata:
      labels:
        app: appdeploy
    spec:
      containers:
        - name: kubecontainer
          image: marcosgiannasio/appdocker:1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb+srv://marcosgiannasio:<password>@cluster0.hqipxhf.mongodb.net/Products?retryWrites=true&w=majority&appName=Cluster0;
          imagePullPolicy: Always